config/routes.rb
Rails.application.routes.draw do
  devise_for :users, path: '', path_names: {
    sign_in: 'login', 
    sign_out: 'logout',
    sign_up: 'register'
  }
  resources :portfolios, except: [:show]
  get 'portfolio/:id', to: 'portfolios#show', as: 'portfolio_show'
  get 'about', to: 'pages#about'
  get 'contact', to:'pages#contact'
  resources :blogs do 
    member do
      get :toggle_status
    end
  end
  root to: 'pages#home'
end

app/models/portfolio.rb
class Portfolio < ApplicationRecord
    include Placeholder
    after_initialize :set_defaults
    validates_presence_of :title, :body, :main_image, :thumb_image
    has_many :technologies
    accepts_nested_attributes_for :technologies, 
                                  reject_if: lambda { |attrs| attrs['name'].blank? }
                                  
    scope :first_five, ->{ last(5).reverse }
    
    def self.first_two
        last(2).reverse
    end
    
    def set_defaults
        self.main_image ||= Placeholder.image_generator(height: 600, width: 400)
        self.thumb_image ||= Placeholder.image_generator(height: 350, width: 200)
    end
    
    def self.by_position
        order("position ASC")
    end
end

app/controllers/portfolios_controller.rb
class PortfoliosController < ApplicationController
    before_action :set_portfolio_item, only: [:show, :edit, :update, :destroy]
    layout 'portfolio'
    access all: [:show, :index], user: {except: [:destroy, :new, :create, :edit, :update]}, site_admin: :all
  
    def index 
        @portfolio_items = Portfolio.by_position
    end
    
    def show 
    end
    
    def new
        @portfolio_item = Portfolio.new
        3.times { @portfolio_item.technologies.build }
        
    end
    
    def create
        @portfolio_item = Portfolio.new(portfolio_params)
        if @portfolio_item.save
            redirect_to portfolios_path
        else
            redirect_to new_portfolio_path
        end
    end
    
    def edit 
    end
    
    def update 
        if @portfolio_item.update(portfolio_params)
            redirect_to portfolios_path
        end
    end
    
    def destroy
        if @portfolio_item.destroy
            redirect_to portfolios_path, notice: 'deleted'
        end
    end
    
    private
    
    def portfolio_params
        params.require(:portfolio).permit(:title, :subtitle, :body, technologies_attributes: [:name])
    end
    
    def set_portfolio_item
        @portfolio_item = Portfolio.find(params[:id])
    end
        
end

app/helpers/portfolios_helper.rb
module PortfoliosHelper
end

app/views/portfolios/_form.html.erb
  <%= form_for(@portfolio_item) do |f| %>
  <div class="row">
    <div class="col-md-6">
      <div class="form-group">
        <%= f.label :title %>
        <%= f.text_field :title, class: 'form-control' %>
      </div>

      <div class="form-group">
        <%= f.label :subtitle %>
        <%= f.text_field :subtitle, class: 'form-control' %>
      </div>
    </div>

    <div class="col-md-6">
      <div class="form-group">
        <%= f.label :body %>
        <%= f.text_area :body, class: 'form-control', rows: 13 %>
      </div>
    </div>
  </div>

  <hr>

  <div class="col-md-12">
    <h2>Technolgies Used:</h2>
    <div>
      <%= f.fields_for :technologies do |technology_form| %>
        <div class="form-group">
          <%= technology_form.label :name %>
          <%= technology_form.text_field :name, class: 'form-control' %>
        </div>
      <% end %>
    </div>

    <div class="form-group">
      <%= f.submit 'Save Portfolio Item', class: 'btn btn-primary btn-block' %>
    </div>
  </div>
<% end %>

app/views/portfolios/_portfolio_item.html.erb
<div class="col-md-4">
    <div class="card mb-4 box-shadow">
        <%= image_tag portfolio_item.thumb_image, class: "card-img-top" unless !portfolio_item.thumb_image %>
        <div class="card-body">
            <p class="card-text">
                <span><%= link_to (truncate portfolio_item.body), portfolio_show_path(portfolio_item) %></span>
                <span><%= portfolio_item.subtitle %></span>
            </p>
        </div>
    </div>
</div>

app/views/portfolios/edit.html.erb
<h1>Edit Portfolio Item</h1>
<%= render 'form', portfolio_item: @portfolio_item %>

app/views/portfolios/index.html.erb
<div class="album py-5 bg-light">
    <div class="container">
        <div class="row sortable">
        <%= render partial: 'portfolio_item', collection: @portfolio_items %>
        </div>
    </div>
</div>

app/views/portfolios/new.html.erb
<h1>Create a new Portfolio Item</h1>

<%= render 'form', portfolio_item: @portfolio_item %>

app/views/portfolios/show.html.erb
<div class="container">
    <div class="row">
        <div class="col-md-7">
            <%= image_tag @portfolio_item.main_image %>
        </div>
        <div class="col-md-5">
            <h1><%= @portfolio_item.title %></h1>
            <hr>
            <em><%= @portfolio_item.subtitle %></em>
            <p><%= @portfolio_item.body %></p>
            
            <h2>Technologies</h2>
            
            <% @portfolio_item.technologies.each do |technology| %>
                <p> <%= technology.name %> </p>
            <% end %>
            <%= link_to "Back to portfolio items", portfolios_path %>
        </div>
    </div>
</div>